openapi: 3.0.3
info:
  title: Valuation API
  version: "1.0.4"
  description: |
    API tra cứu thông tin định giá bất động sản

servers:
  - url: http://localhost:8000
    description: Local FastAPI server

paths:
  /projects:
    post:
      summary: Tra cứu thông tin dự án
      description: Nhập tên dự án để tra cứu thông tin và danh sách các phân khu (nếu có)
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                project_name:
                  type: string
      responses:
        "200":
          description: Thông tin dự án và danh sách phân khu
          content:
            application/json:
              schema:
                type: object
                properties:
                  project:
                    $ref: "#/components/schemas/Project"
                  sectors:
                    type: array
                    items:
                      $ref: "#/components/schemas/Sector"
        "404":
          description: Không tìm thấy dự án phù hợp
        "500":
          description: Lỗi hệ thống. Vui lòng thử lại sau.

  /sectors:
    post:
      summary: Tra cứu phân khu thuộc dự án
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                project_name:
                  type: string
                sector_name:
                  type: string
      responses:
        "200":
          description: Thông tin phân khu và danh sách tháp thuộc phân khu
          content:
            application/json:
              schema:
                type: object
                properties:
                  sector:
                    $ref: "#/components/schemas/Sector"
                  towers:
                    type: array
                    items:
                      $ref: "#/components/schemas/Tower"
        "404":
          description: Không tìm thấy phân khu trong dự án
        "409":
          description: Phân khu không thuộc dự án được chọn
        "500":
          description: Lỗi hệ thống. Vui lòng thử lại sau.

  /towers:
    post:
      summary: Tra cứu tháp theo phân khu
      description: Nhập tên phân khu và tên tháp (tuỳ chọn) để lấy danh sách tầng
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                sector_name:
                  type: string
                tower_name:
                  type: string
      responses:
        "200":
          description: Thông tin tháp và danh sách tầng thuộc tháp đó
          content:
            application/json:
              schema:
                type: object
                properties:
                  tower:
                    $ref: "#/components/schemas/Tower"
                  floors:
                    type: array
                    items:
                      $ref: "#/components/schemas/Floor"
        "404":
          description: Không tìm thấy tháp trong phân khu này
        "500":
          description: Lỗi hệ thống. Vui lòng thử lại sau.

  /floors:
    post:
      summary: Tra cứu tầng theo tháp
      description: Nhập tên tháp để xem danh sách tầng, hoặc nhập tầng cụ thể để xem chi tiết
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                tower_name:
                  type: string
                floor_number:
                  type: string
      responses:
        "200":
          description: Thông tin tầng và danh sách căn hộ
          content:
            application/json:
              schema:
                type: object
                properties:
                  floor:
                    $ref: "#/components/schemas/Floor"
                  apartments:
                    type: array
                    items:
                      $ref: "#/components/schemas/Apartment"
        "404":
          description: Không tìm thấy tầng trong tháp này
        "500":
          description: Lỗi hệ thống. Vui lòng thử lại sau.

  /apartments:
    post:
      summary: Tra cứu căn hộ theo tầng
      description: Nhập tên tháp và số tầng để lấy danh sách căn hộ
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                tower_name:
                  type: string
                floor_number:
                  type: string
                apartment_name:
                  type: string
      responses:
        "200":
          description: Thông tin căn hộ và dữ liệu định giá
          content:
            application/json:
              schema:
                type: object
                properties:
                  apartment:
                    $ref: "#/components/schemas/Apartment"
                  pricing:
                    $ref: "#/components/schemas/PropertyPrice"
        "404":
          description: Không tìm thấy căn hộ trong tầng này
        "500":
          description: Lỗi hệ thống. Vui lòng thử lại sau.

  /pricing:
    post:
      summary: Tra cứu giá căn hộ
      description: Nhập thông tin căn hộ để lấy giá định giá chi tiết
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                apartment_name:
                  type: string
                floor_number:
                  type: string
                tower_name:
                  type: string
                has_furniture:
                  type: boolean
      responses:
        "200":
          description: Thông tin chi tiết định giá và đặc điểm căn hộ
          content:
            application/json:
              schema:
                type: object
                properties:
                  apartment:
                    $ref: "#/components/schemas/Apartment"
                  pricing:
                    $ref: "#/components/schemas/PropertyPrice"
        "404":
          description: Không tìm thấy giá cho căn hộ này
        "409":
          description: Giá trị định giá không hợp lệ
        "500":
          description: Lỗi hệ thống. Vui lòng thử lại sau.

components:
  schemas:
    Project:
      type: object
      properties:
        project_name:
          type: string
        

    Sector:
      type: object
      properties:
        sector_name:
          type: string

    Tower:
      type: object
      properties:
        tower_name:
          type: string

    Floor:
      type: object
      properties:
        floor_number:
          type: string 

    Apartment:
      type: object
      properties:
        apartment_name:
          type: string

    PropertyPrice:
      type: object
      properties:
        appraised_value:
          type: number
          format: float
        opening_price:
          type: number
          format: float
        negotiable_price:
          type: number
          format: float
        value_after_furnishing:
          type: number
          format: float
        status:
          type: string
          
